#!/usr/bin/env bash

rm ~/.local/share/rofi/themes/Mint-Y-Dark-Aqua.rasi &
rm ~/.local/share/rofi/themes/Mint-Y-Dark-Blue.rasi &
rm ~/.local/share/rofi/themes/Mint-Y-Dark-Brown.rasi &
rm ~/.local/share/rofi/themes/Mint-Y-Dark-Green.rasi &
rm ~/.local/share/rofi/themes/Mint-Y-Dark-Grey.rasi &
rm ~/.local/share/rofi/themes/Mint-Y-Dark-Orange.rasi &
rm ~/.local/share/rofi/themes/Mint-Y-Dark-Pink.rasi &
rm ~/.local/share/rofi/themes/Mint-Y-Dark-Purple.rasi &
rm ~/.local/share/rofi/themes/Mint-Y-Dark-Red.rasi &
rm ~/.local/share/rofi/themes/Mint-Y-Dark-Sand.rasi &
rm ~/.local/share/rofi/themes/Mint-Y-Dark-Teal.rasi &
rm ~/.local/share/rofi/themes/Mint-Y-Light-Aqua.rasi &
rm ~/.local/share/rofi/themes/Mint-Y-Light-Blue.rasi &
rm ~/.local/share/rofi/themes/Mint-Y-Light-Brown.rasi &
rm ~/.local/share/rofi/themes/Mint-Y-Light-Green.rasi &
rm ~/.local/share/rofi/themes/Mint-Y-Light-Grey.rasi &
rm ~/.local/share/rofi/themes/Mint-Y-Light-Orange.rasi &
rm ~/.local/share/rofi/themes/Mint-Y-Light-Pink.rasi &
rm ~/.local/share/rofi/themes/Mint-Y-Light-Purple.rasi &
rm ~/.local/share/rofi/themes/Mint-Y-Light-Red.rasi &
rm ~/.local/share/rofi/themes/Mint-Y-Light-Sand.rasi &
rm ~/.local/share/rofi/themes/Mint-Y-Light-Teal.rasi &
echo Done, the Rofi Mint-Y theme has gone



